# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alycgaut <alycgaut@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/23 17:02:44 by alycgaut          #+#    #+#              #
#    Updated: 2022/07/23 17:35:30 by alycgaut         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	= 	main.c	\
				ft_atoi.c	\
				ft_check_argument.c 	\

OBJS = ${SRCS:.c=.o}

NAME = rush-02

all :	${OBJS}
		cc -o ${NAME} ${OBJS}

	